### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by wxAlpha** [ClimateGlobalChange/tempestextremes#10]
Thank you for developing this tracking algorithm. I am working on monsoon depression tracking and I found this algorithm could be really helpful.

But when I build with command "make LDFLAGS="-L/home/ty/software/lib" ,it takes error:
`mpiCC -L/home/ty/software/lib -o StitchBlobs /home/ty/TRACK/tempestextremes/src/blobs/build/StitchBlobs.o ../../src/base/libextremesbase.a -lnetcdf -lnetcdf_c++
/usr/bin/ld: /home/ty/TRACK/tempestextremes/src/blobs/build/StitchBlobs.o: undefined reference to symbol 'cos@@GLIBC_2.2.5'
/usr/lib64/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:29: recipe for target 'StitchBlobs' failed`

**_The mpicc information is attached_**
mpicc for MPICH2 version 1.4.1p1
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/6.4.1/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,objc,obj-c++,fortran,ada,go,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --disable-libgcj --with-isl --enable-libmpx --enable-gnu-indirect-function --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 6.4.1 20170727 (Red Hat 6.4.1-1) (GCC)

Any help is appreciated!!

**Comment by paullric** [comment]
Hi Yujia -- yikes, that looks like a linking error with the gnu C library.
I think there is a deeper issue with how you are conducting builds.  Make
sure you modify mk/system.make and the corresponding system configuration
in mk/system/ to be consistent with your build environment.

**Comment by wxAlpha** [comment]
Hi Paul,

Many thanks!!

I modified the mk/system and install the netcdf_cxx_4.2 (I have higher version originally), the compile now goes elegantly!
