### ISSUE TITLE
Preserve dimension definition variables in NodeFileFilter

### ISSUE THREAD

**Issue by zarzycki** [ClimateGlobalChange/tempestextremes#11]
Currently output of NodeFileFilter preserves the time dimension variable for .nc output but does not preserve horizontal/vertical dimension(s) variable(s). This is a trivial operation for standard lat/lon grids; might be a bit more tricky for unstructured meshes. Suggest some arbitrary logic such as...

if (input data has var "lat" or "latitude" or "LAT" or "lat_0" ...) then
                // Copy lat
                CopyNcVar(ncinfile, ncoutfile, "THE_LAT_VAR_NAME");
end if

near Line 503 in NodeFileFilter.cpp

such that output has associated...

lat(lat)
lon(lon)

etc. coords for direct indexing use in tools like NCO, ncview, NCL, python, etc.

**Comment by paullric** [comment]
Should now be fixed in commit 54d998dfaaaa28466d0fa0b1301a07d0edf32c34.  New command line option added to NodeFileFilter "--preserve" that preserves a comma-delimited list of variables.  Also automatically preserves "lat", "latitude", "lat_0", "LAT", "lon", "longitude", "lon_0", "LON".

**Comment by zarzycki** [comment]
Currently working for my flow, so closing this.
