### ISSUE TITLE
NodeFileFilter should write missing values instead of 0 for masked var

### ISSUE THREAD

**Issue by zarzycki** [ClimateGlobalChange/tempestextremes#14]
Currently NodeFileFilter writes "0" to *nc for the portions of the domain that are during masking. For the binary mask var (0 or 1), this is logical, but if you are masking an atmospheric variable (i.e., PRECT) NFF should actually write *nc missing values.

Assume keeping PRECT inside TC radius. Resulting PRECT_MASK may have a "true" 0 that lies inside the acceptable radius (i.e., valid grid point but no rain). It may also have "false" 0s that like outside the radius (may be raining, but invalid gridpoint due to being too far away from TC). We should differentiate between the two.

**Comment by paullric** [comment]
Added NodeFileFilter --fillvalue argument in commit c8171d3.

This argument switches the application of the mask to any command-line variables to use binary logic:  If mask = 1 then use input data value, if mask = 0 use --fillvalue.  The --fillvalue argument may also be "nan" which produces a float nan for regions of 0 mask or "att" which attempts to use the _FillValue for the given variable for regions of 0 mask.

**Comment by zarzycki** [comment]
Tested with --fillvalue "att" and --fillvalue -9999.9 and behavior seems as expected, with packages that have _FillValue support properly filtering out the masked field, so I'd consider this closed for now.
