### ISSUE TITLE
Adding a bounded --pct_overlap in StitchBlobs

### ISSUE THREAD

**Issue by zarzycki** [ClimateGlobalChange/tempestextremes#15]
Currently StitchBlobs uses --pct_overlap to enforce a minimum overlap (i.e., two blobs need to overlap by a certain percentage at successive times to constitute the same blob). In looking at MCS, Julie Caron has noted that there may be utility in also enforcing a maximum limit, which would "force" a feature to move (i.e., quasi-stationary or stationary features would be thrown out). This is somewhat analogous to min_endpoint_dist in SN, although enforced step-by-step.

I think there's more obvious use cases for making sure features aren't moving too fast, but for something like nocturnal, propagating MCS, you clearly would like to filter out stationary phenomenon. A similar use case could be using blob tracking for easterly tropical waves or MJO-induced OLR anomalies.

This should be a pretty trivial kernel addition. Perhaps leave --pct_overlap for backwards portability and just add something like --max_pct_overlap?

**Comment by paullric** [comment]
Added in the latest version of StitchBlobs.  --pct_overlap is now broken up into four arguments:

--min_overlap_prev [%]:  in order for two blobs to be connected in time, the blob at the next time step must overlap at least this % of the previous time step’s blob
--max_overlap_prev [%]:  in order for two blobs to be connected in time, the blob at the next time step must overlap at most this % of the previous time step’s blob
--min_overlap_next [%]:  in order for two blobs to be connected in time, the blob at the previous time step must overlap at least this % of the next time step’s blob
--max_overlap_next [%]:  in order for two blobs to be connected in time, the blob at the previous time step must overlap at most this % of the next time step’s blob
