### ISSUE TITLE
Time edits in cb21453 break NodeFileFilter

### ISSUE THREAD

**Issue by zarzycki** [ClimateGlobalChange/tempestextremes#19]
This commit -- cb21453 -- breaks NodeFileEditor. Previously

`${TEMPESTEXTREMESDIR}/bin/NodeFileFilter --in_nodefile ${TRAJFILENAME} --in_fmt "lon,lat,slp,slp,phis" --in_data_list ${NODELISTNAME} --out_data_list ${NODELISTNAMEFILT} --var "pr" --nearbyblobs "pr,2.0,>=,10.0e-5,40.0" --maskvar "mask"`

worked as expected to mask certain "blobs" near the node... now this error gets thrown:

..EXCEPTION (/Users/cmz5202/Software/tempestextremes/src/base/NetCDFUtilities.cpp, Line 289) Cannot create variable "time"

Reverting to the commit prior to the above linked changes results in expected behavior.

**Comment by paullric** [comment]
Testing fix in commit 710a6e7dc0521a5aec4446208fab417fa6ba3a39

**Comment by zarzycki** [comment]
So that appears to address the issue of double writing time but another one pops up a few lines later. I'll just call this "same bug" since they are related and I'm too lazy to do a PR.

If you don't set --preserve it defaults to "" -- but then NFF goes and tries to find a var named "" on the input .nc file using ncCopyVar and chokes with the below error.

`..EXCEPTION (/Users/cmz5202/Software/tempestextremes/src/base/NetCDFUtilities.cpp, Line 148) NetCDF file does not contain variable ""`

This can be circumvented by not passing an empty string to --preserve and keeping some constant var from the input -> output data (ex: --preserve "time_bnds"). However, a real solution is probably just to test for an empty string in src/base/NetCDFUtilities.cpp since there doesn't seem to be an actual case where anyone would name a valid var with an empty string.

**Comment by paullric** [comment]
Should be fixed in commit 26da4c8215c2988489b4bc38f1c850c11b58d6be

**Comment by zarzycki** [comment]
Looks good!
