### ISSUE TITLE
NodeFileFilter fails with "assertion error" if a variable has an empty string for attribute

### ISSUE THREAD

**Issue by zarzycki** [ClimateGlobalChange/tempestextremes#33]
Netcdf 4.8.0 on MacOS.

Some WRF variables have attributes such as "stagger" -- for some runs (HF TGW, for example) this variable is just an empty string.

```
	float SLP(time, south_north, west_east) ;
		SLP:description = "Sea Level Pressure" ;
		SLP:units = "hPa" ;
		SLP:coordinates = "XLONG XLAT XTIME" ;
		SLP:stagger = "" ;
		SLP:MemoryOrder = "XYZ" ;
		SLP:FieldType = 104 ;
```

When running NFF with multiple variables passed in...

Ex:

```
${TEMPESTEXTREMESDIR}/bin/NodeFileFilter --in_nodefile 2005_test.txt --in_fmt "lon,lat,pres,wind,phis" --in_data_list "precip_file_list.txt" --out_data_list "precip_output_files.txt" --bydist 5.0 --var "SLP,U10,V10,OLR" --preserve "XLAT,XLONG" --regional --fillvalue "nan" --maskvar "mask" --latname "XLAT" --lonname "XLONG"
```

TE will fail with the following error:

```
Processing input (/Users/cmz5202/NetCDF/TGW/aux/wrfout_d01_2005-06-11_00:00:00_3hourly.aux.nc)
..EXCEPTION (/Users/cmz5202/Software/tempestextremes/src/base/NetCDFUtilities.cpp, Line 153) Assertion failure
```

If one deletes the empty attribute from all vars on the file, such as:

```
ncatted -O -a stagger,,d,, aux/wrfout_d01_2005-06-11_00\:00\:00_3hourly.aux.nc aux/wrfout_d01_2005-06-11_00\:00\:00_3hourly.aux.nc 
```

TE is successful.

**Comment by zarzycki** [comment]
Yes, commenting out that line in NetCDFUtilities does avoid the issue.

I'm trying to think of edge cases where having that _ASSERT is helpful -- I suppose you could only call the _ASSERT on non-char attributes to handle this particular problem?

But for now, removing that is an alternative to using NCO to modify the files (have TE handle that would probably be preferable in the long run anyways...)

**Comment by paullric** [comment]
Removed _ASSERT in commit a361e4fb5d8606517d66233eba15132fefdfbed2
