### ISSUE TITLE
Compile errors with intel

### ISSUE THREAD

**Issue by zarzycki** [ClimateGlobalChange/tempestextremes#4]
Trying to compile on Yellowstone with same Makefile (intel 12.5.0) as before MPI implementation...

--------

/glade/p/work/zarzycki/tempestextremes/src/nodes/DetectCyclonesUnstructured.cpp(2016): error: no instance of constructor "std::basic_ifstream<_CharT, _Traits>::basic_ifstream [with _CharT=char, _Traits=std::char_traits<char>]" matches the argument list
            argument types are: (std::string)
  		std::ifstream ifInputFileList(strInputFileList);
  		                              ^

/glade/p/work/zarzycki/tempestextremes/src/nodes/DetectCyclonesUnstructured.cpp(2038): error: no instance of constructor "std::basic_ifstream<_CharT, _Traits>::basic_ifstream [with _CharT=char, _Traits=std::char_traits<char>]" matches the argument list
            argument types are: (std::string)
  		std::ifstream ifOutputFileList(strOutputFileList);
  		                               ^

compilation aborted for /glade/p/work/zarzycki/tempestextremes/src/nodes/DetectCyclonesUnstructured.cpp (code 2)
make[1]: *** [/glade/p/work/zarzycki/tempestextremes/src/nodes/build/DetectCyclonesUnstructured.o] Error 2

**Comment by paullric** [comment]
Pushed a fix that uses the standard ifstream constructor.  The code now seems to build on Yellowstone without issue.  Please verify and close.

~ Paul

**Comment by zarzycki** [comment]
That has corrected the compile issues.
