### ISSUE TITLE
Question regarding application to GCMs

### ISSUE THREAD

**Issue by krober10nd** [ClimateGlobalChange/tempestextremes#42]
Hi, I'm comparing TC track results from the following article with those obtained from TE using the same GCM inputs.

https://wcd.copernicus.org/articles/3/1359/2022/wcd-3-1359-2022.html

specifically I'm using the recommended criteria based on the sensitivity analysis for tracking TCs in reanalysis datasets: 

<img width="535" alt="Screenshot 2023-02-08 at 9 07 05 AM" src="https://user-images.githubusercontent.com/18619644/217525384-561ebdd4-593c-4afa-8630-518404e41100.png">

<img width="549" alt="Screenshot 2023-02-08 at 9 07 40 AM" src="https://user-images.githubusercontent.com/18619644/217525503-a970251b-d2e5-47fc-8ef3-99d1f882200d.png">

but omitting the surface wind criteria (due to GCM 6hrPtPlev data availability).

However, in the North Atlantic basin using TE for the historical period, I'm obtaining only a handful (~5)  tracks over 1984-2015. This is contrasting significantly with the result from the article referenced at the top of this issue. For example just focusing on the MIROC6:

<img width="923" alt="Screenshot 2023-02-08 at 9 09 19 AM" src="https://user-images.githubusercontent.com/18619644/217525832-65fec35d-abdd-4f49-bb79-087f294b45d6.png">

I wanted to know if you had any thoughts on how this difference could be reconciled using TE with these inputs? Perhaps the warm core criteria and pressure thresholds should be relaxed for application to these coarser resolutions? I realize GCMs at this resolution struggle to represent TCs; however, the differences in TC density between TE and Hodges' Tracker here are off by nearly a factor of 10-15x. 

Thanks for any thoughts,

Keith

**Comment by zarzycki** [comment]
Hi Keith,

My first blush thought is those configurations you have screenshot above appear to be for extratropical cyclone tracking over the North Atlantic. For TCs you will want a warm core check (we've been using DZ300500 based on [Zarzycki ad Ullrich, 2017](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2016GL071606), but you can also use either a single (less ideal) or average (more ideal) of upper-air temperatures on a constant pressure surface). You'll also want to broadly remove that domain dependence in StitchNodes -- typically we find it most successful in "boxing" storm trajectories but for rigorous basin analysis it's better to use a post-tracking filter.

One thing that may be helpful is the [CyMeP](https://github.com/zarzycki/cymep) package ([Zarzycki et al., 2021](https://journals.ametsoc.org/view/journals/apme/60/5/JAMC-D-20-0149.1.xml)), which builds over the top of TempestExtremes for analyzing climate model data. It also contains a sample TempestExtremes tracker script.

A last suggestion (in addition to CyMeP above) is that [Roberts et al., 2020](https://journals.ametsoc.org/view/journals/clim/33/7/jcli-d-19-0639.1.xml) also compared TempestExtremes and TRACK for climate model output. In general, it was found TRACK detected more TCs in a given dataset than TE.

Anecdotally, I have found that TRACK hit rates tend to be slightly higher on reanalysis than TE, but the false alarm rates are a fair bit higher, so the overall skill (e.g., Critical Skill Index) tends to be better for TE. Intense TCs are nearly identically matched using both algorithms. TRACK may be more suitable for fully sampling storm lifetime (e.g., pre-genesis) at the expense of "false" detections of subtropical or extratropical (warm seclusion) lows. There are ways you can configure TE to behave somewhat like TRACK and I assume vice-versa is also true :)

**Comment by krober10nd** [comment]
Thank you @zarzycki ! This is very helpful. Yes sorry I screenshotted the random snippets, I am using the warm core criteria. Could also elaborate on how one might accomplish this? 

```
You'll also want to broadly remove that domain dependence in StitchNodes -- typically we find it most successful in "boxing" storm trajectories but for rigorous basin analysis it's better to use a post-tracking filter.
```

Really appreciate the `CyMeP` package reference. I will check it out!

**Comment by krober10nd** [comment]
Thanks for the quick response. 

Ah yes, I understand. I was using these were the commands previously (I screenshotted the wrong parts of the paper above). 

![image](https://user-images.githubusercontent.com/18619644/217569548-3d1f499c-001d-46e3-a5ac-ce22bd1fac41.png)
![image](https://user-images.githubusercontent.com/18619644/217569620-90d1f463-1475-4ad9-ae78-9a9efe083bb9.png)
