### ISSUE TITLE
0 everywhere with filtercmd command

### ISSUE THREAD

**Issue by wreckdump** [ClimateGlobalChange/tempestextremes#44]
I am getting 0 everywhere with filtercmd command.

My command is like the following

./DetectBlobs --in_data ncp.sample.Tb.trp.qd.havg.nc --out sample.nc --filtercmd "Tb,<,240,1" 

The input field is brightness temperature in the tropical area (30S - 30N). I get a desired results with --thresholdcmd. But, I would like to use the output from --filtercmd rather than the --thresholdcmd.

**Comment by paullric** [comment]
--filtercmd removes areal features that have already been detected by thresholdcmd which do not satisfy some sort of filter criteria.  In the example below there would be nothing detected, so there is nothing to be filtered.  Why do you want to use filtercmd instead?

**Comment by wreckdump** [comment]
So you are saying filtercmd calls thresholdcmd first and then additionally filters what is specified in the command?

What I understand from the documentation (https://climate.ucdavis.edu/tempestextremes.php), I got the impression that the filtercmd option only filters any pixels that are specified. In the command that I've used I expected any brightness temperature pixels, within 1 pixel, that are less than 240K to be filtered. I've also tried "Tb,<,240,10" to make the grid points larger, but I am getting the same results.

**Comment by paullric** [comment]
Yes, filtercmd removes any blobs detected after thresholding that don't satisfy a particular filter criteria.  But they need to be detected first by thresholding.  I'm not 100% clear on what you're trying to do.  Would it be ok to use DetectBlobs to detect these blobs and then use VariableProcessor to calculate 1 minus the binary_tag?

**Comment by wreckdump** [comment]
Okay. I understand. I was expecting just simple threshold filter from filtercmd option (something like the attached figure).
![filter_sample](https://user-images.githubusercontent.com/26279723/221035890-7d48d5f1-f430-4e63-8a93-709a9415486d.png)

I guess I should just use thresholdcmd for my purpose.

**Comment by paullric** [comment]
It would be easy enough to add an “—invert” argument to DetectBlobs if that would be desirable?

**Comment by wreckdump** [comment]
I don't think that would be neccessary. Thank you though.
