### ISSUE TITLE
TempestExtremes skipping

### ISSUE THREAD

**Issue by krober10nd** [ClimateGlobalChange/tempestextremes#45]
Hello, I am tracking tropical cyclones in GCMs using the following command 

![image](https://user-images.githubusercontent.com/18619644/220689665-120ca2c5-2c16-4152-84fb-f6ae3d4e2c9d.png)

with the following inputs 
![image](https://user-images.githubusercontent.com/18619644/220689798-c672a876-4809-42a1-a8f3-9aabdaff8e0b.png)

This approach works in other GCMs but for NorESM, TE skips through all the input files. 

![image](https://user-images.githubusercontent.com/18619644/220690108-c59aaa06-8c60-407b-878c-cacfda2e62ac.png)

I have tried relaxing the criteria (to even just low pressure systems) but nothing is detected. Maybe something I'm missing? 

Thank you,

**Comment by paullric** [comment]
Looks like NorESM outputs six hourly starting at 03:00:00.  The —timefilter “6hr” looks for outputs at time 00:00:00, 06:00:00, 12:00:00 and 18:00:00.  Specifically it is equivalent to this:

--timefilter "....-..-.. (00|06|12|18):00:00"

You can run on the time steps provided by NorESM by using this command instead:

--timefilter "....-..-.. (03|09|15|21):00:00"
