### ISSUE TITLE
Computing quadrant-based TC radius to gales

### ISSUE THREAD

**Issue by krober10nd** [ClimateGlobalChange/tempestextremes#46]
Hello, Reading the paper I see there's this functionality to calculate storm relative quantities using the `NodalFileEditor` was curious if anyone had applied TE to calculate R34 (radius to gales) extents in a quadrant based approach  (e.g., NE, NW, SW, SE quadrants) using ERA5 or if this could be done with existing commands somehow? Thank you for any thoughts.

**Comment by paullric** [comment]
There isn’t any support at the moment for quadrants, but this could be added as a feature request.

You could also use the radial composition capability from NodeFileCompose, but this would require a bit extra work to get radius to gales.

**Comment by krober10nd** [comment]
thanks Paul, how do I go about adding a feature request? I think this could be useful.

I'm working on a project that involves blending TC vortices (using a Holland 2010 vortex model) into ERA5 reanalysis data and we'd like to augment IBTraCS best track data with information obtained from ERA5 so the blending works smoothly.

**Comment by paullric** [comment]
Explaining the desired functionality here would be fine.  If you provide a
clear explanation of what is desired and are willing to test it, it should
be easy enough.

**Comment by krober10nd** [comment]
Okay let me know if this isn't clear enough: 

Feature Request: "Extension of Storm-centered radial profile analysis in NodalFileEditor"

Description: Extend NodalFileEditor's radial_profile function for computing the radial profile of a variable for each timestep, based additionally on an angle orientation relative to the center of a storm. The angle parameter of the radial_profile function would ideally accept an array of angles and list each radial profile in a logical order in a csv output file. 

Purpose: This extension of the existing functionality of radial_profile can be used to analyze storm asymmetry in a quadrant-based fashion.

**Comment by krober10nd** [comment]
Following up on this, I went to go compute the azimuthal wind profile for some tracks on the northwest shelf of Australia and the radial wind profile is coming back with negative values.

 I did the following: 

# Track the storms
```
#!/bin/bash

/Users/keithroberts/codes/tempestextremes/bin/DetectNodes --in_data_list ERA5_files.txt --timefilter "6hr" --out_file_list ERA5_TC_candidates.txt --searchbymin msl --closedcontourcmd "msl,200.0,5.5,0;_DIFF(z(300millibars),z(500millibars)),-58.8,6.5,1.0" --diag_connect --mergedist 6.0 --outputcmd "msl,min,0;_VECMAG(u10,v10),max,2" --latname "latitude" --lonname "longitude" --regional

```

# Stitch the points together 
```
#/bin/bash
/Users/keithroberts/codes/tempestextremes/bin/StitchNodes --in_list ERA5_TC_candidates.txt  --out ERA5_TC_Tracks.txt --in_fmt "lon,lat,slp,wind" --range 8.0 --mintime "54h" --maxgap "24h" --threshold "lat,<=,50.0,10;lat,>=,-50.0,10"
```

# Compute the radial profile 
```
#!/bin/bash

/Users/keithroberts/codes/tempestextremes/bin/NodeFileEditor --in_data_list ERA5_files.txt --in_nodefile ERA5_TC_Tracks.txt --in_fmt "lon,lat,slp,wind" --out_nodefile ERA5_TC_radprofs.txt --out_fmt "lon,lat,rsize,rprof" --timefilter "6hr" --calculate "rprof=radial_wind_profile(u10,v10,159,0.125);rsize=lastwhere(rprof,>,17)" --latname "latitude" --lonname "longitude" --regional
```

The azimuthal profile of wind appears to be negative at times in the output file. I'm not sure how this possible?  Or am I doing something incorrectly here? 

For example an excerpt from the output file (and see the attached file for the full record)
```
start	29	1979	2	25	6
	205	48	130.250000	-13.780000	0.000000e+00	"[0.000000e+00,-9.981095e-01,1.075283e+00,2.238870e+00,1.783967e+00,4.214080e+00,1.976047e+00,2.389477e+00,2.715098e+00,2.433495e+00,3.455613e+00,0.000000e+00,3.717574e+00,4.497976e+00,3.725257e+00,1.391733e+00,3.288046e+00,3.288046e+00,3.916605e+00,4.938724e+00,5.044939e+00,3.106917e+00,5.528249e+00,5.528249e+00,5.640570e+00,6.349506e+00,5.717402e+00,3.667425e+00,5.923385e+00,6.434144e+00,5.882774e+00,4.309887e+00,5.571055e+00,5.571055e+00,5.258239e+00,5.258239e+00,5.119942e+00,5.637286e+00,5.273606e+00,3.875238e+00,5.569226e+00,5.569226e+00,5.768624e+00,6.446095e+00,5.822040e+00,3.843041e+00,5.799722e+00,6.609516e+00,5.987411e+00,6.098635e+00,6.077781e+00,6.075220e+00,6.180589e+00,6.114733e+00,6.211688e+00,6.208395e+00,6.149490e+00,6.157540e+00,6.110343e+00,5.995461e+00,5.970582e+00,5.764965e+00,5.759477e+00,5.598861e+00,5.694718e+00,5.537030e+00,5.544713
[ERA5_TC_radprofs.txt](https://github.com/ClimateGlobalChange/tempestextremes/files/11133934/ERA5_TC_radprofs.txt)
e+00,5.325559e+00,5.261898e+00,4.873347e+00,4.700658e+00,4.090026e+00,4.062586e+00,3.410611e+00,3.248898e+00,2.849371e+00,2.599118e+00,2.554483e+00,2.281912e+00,2.401550e+00,2.195933e+00,1.891532e+00,1.552373e+00,1.065039e+00,8.630800e-01,1.589326e+00,1.493834e+00,2.326914e+00,2.218251e+00,2.384355e+00,2.264716e+00,1.811407e+00,1.682256e+00,1.000646e+00,8.916176e-01,4.694072e-01,4.287960e-01,-5.524836e-01,-4.068685e-01,-4.068685e-01,-4.478456e-01,-4.478456e-01,-7.222458e-01,-7.222458e-01,-9.242043e-01,-9.242043e-01,-7.573690e-01,-7.573690e-01,4.973337e-02,4.973337e-02,1.027330e+00,1.027330e+00,1.698330e+00,1.698330e+00,1.967608e+00,1.967608e+00,2.017366e+00,2.017366e+00,2.060538e+00,2.060538e+00,2.097125e+00,2.097125e+00,2.314450e+00,2.314450e+00,2.334938e+00,2.334938e+00,2.143956e+00,2.143956e+00,1.948583e+00,1.948583e+00,1.909069e+00,1.909069e+00,2.025415e+00,2.025415e+00,2.120540e+00,2.120540e+00,2.047367e+00,2.047367e+00,2.287375e+00,2.287375e+00,3.222531e+00,3.222531e+00,4.588678e+00,4.588678e+00,4.666242e+00,4.149638e+00,3.633034e+00,2.926179e+00,2.926179e+00,2.752026e+00,2.752026e+00,2.500310e+00,2.500310e+00,2.411038e+00,2.411038e+00,2.138102e+00,2.138102e+00,1.932484e+00,1.932484e+00]"	1979
```

**Comment by krober10nd** [comment]
Upon reviewing the code, it seems the sign indicates cyclonic or anti-cyclonic activity and the velocity components are projected onto a vector.

 I suppose then to calculate the windspeed azimuthal profile, I need to add a new variable to the NetCDF files containing the magnitude of winds at the surface and use `radial_profile` instead?
 
 I tried 

```
 /Users/keithroberts/codes/tempestextremes/bin/NodeFileEditor --in_data_list ERA5_files.txt --in_nodefile ERA5_TC_Tracks.txt --in_fmt "lon,lat,slp,wind" --   out_nodefile ERA5_TC_radprofs.txt --out_fmt "lon,lat,rsize,rprof" --timefilter "6hr" --calculate "windpseed=_VECMAG(u10,v10),max,2;                          rprof=radial_profile(windspeed,159,0.125);rsize=lastwhere(rprof,>,17)" --latname "latitude" --lonname "longitude" --regional
```

but _VECMAG isn't permitted in this operation. 

Thanks

**Comment by krober10nd** [comment]
I solved this with existing features by adding a wind magnitude variable to surface ERA5 files, extracting storm-centric snaps of the surface winds using `NodeFileCompose` 

```
 #!/bin/bash
 
 /Users/keithroberts/codes/tempestextremes/bin/NodeFileCompose --in_nodefile ERA5_TC_Tracks.txt --in_nodefile_type 'SN' --in_fmt "lon,lat,slp,wind" --        in_data_list ERA5_files.txt --diag_connect --regional --out_grid "XY" --resx 61 --out_data "ERA_TC_Tracks_composed_V2.nc" --var "wind_mag,msl" --            snapshots --op "max" --lonname "longitude" --latname "latitude" --fixlon -999.0 --fixlat -999.0
```

and reading in that netcdf file in Python and then finding the distance to a closed contour representing gale force winds for each snap.


![snap_wind_mag_2018032118](https://user-images.githubusercontent.com/18619644/233751988-074faa6d-189c-48f2-85a1-bd05e6cdc656.png)
