### ISSUE TITLE
Clarification on Matching ERA5 and IBTrACS Cyclone Tracks in TempestExtremesV2

### ISSUE THREAD

**Issue by krober10nd** [ClimateGlobalChange/tempestextremes#48]
In your article in GMD about TempestExtremesV2 you mention matching tropical cyclone tracks obtained via tracking using ERA5 data and IBTrACS. I am curious about how the tracks from ERA5 were matched with those in IBTrACS as I have to do something similar. Could you provide any information or guidance on this topic?

Thanks,

Keith

**Comment by zarzycki** [comment]
We did this analysis in both [Zarzycki and Ullrich (2017)](http://dx.doi.org/10.1002/2016GL071606) and [Zarzycki et al., 2021](http://dx.doi.org/10.1175/JAMC-D-20-0149.1).

In the [CyMeP](https://github.com/zarzycki/cymep) repo is [the (admittedly unorganized/unclean) NCL that was used to do that](https://github.com/zarzycki/cymep/blob/master/ncl/new-hit-rate.ncl). @stella-bourdin may have Python to do this as part of [her recent paper](https://gmd.copernicus.org/articles/15/6759/2022/).

Essentially, you have to decide exactly how you want to match the tracks. You can either match each 6-hourly point and call the fraction of IBTrACS points that match TempestExtremes points your hits *or* you go storm by storm and define some minimum criteria to define that entire storm as a hit (e.g., if >=1 point along that track matches, the entire storm is a hit). The former more heavily weights storms that live longer (not ideal) but the latter obviously provides a pretty low bar for a hit (i.e., you could score extremely well matching only 1 out of 50 points during a TC lifecycle). We applied the former in ZU17 and the latter in Z21. Depending on your "reference" dataset, you may want to consider filtering low-quality or weak events if desirable, although this should be explicitly noted in any documentation.

In practice, we've actually found there to be minimal different when using either approach to *compare* two datasets (i.e., one that scores highly with one strategy scores highly with the other).

**Comment by krober10nd** [comment]
Thank you! This is helpful. I’ll try out both methods and report back how they worked.

**Comment by stella-bourdin** [comment]
Hello, 
I am arriving late, but I indeed have code to do that, that I used for our [tracker intercomparison paper](https://gmd.copernicus.org/articles/15/6759/2022/gmd-15-6759-2022.html).
The code is here:
https://github.com/stella-bourdin/dynamicoPy/blob/main/dynamicopy/tc/matching.py
Don't hesitate to contact me via email if you want more information, as I am not closely monitoring GitHub...
Stella

**Comment by krober10nd** [comment]
Thanks Stella. I worked out a semi automated approach that involved comparing the Hausdorff distance between candidate matches and then me going in an doing some sanity checking.
