### ISSUE TITLE
Support for absminlat

### ISSUE THREAD

**Issue by zarzycki** [ClimateGlobalChange/tempestextremes#5]
For tracking ETCs, would be nice to recover the old functionality of minlat...

ex: --absminlat 30.0   ---> only keeps detections lat >= abs(30.0)

**Comment by zarzycki** [comment]
Note: this would be preferable over filtering by lat in StitchNodes because long-lived TC trajectories (that undergo ET and becomes ETCs) are almost impossible to filter with threshold criteria over X steps unless. A "hard" lat limit does a better job producing a reasonable ETC climatology without having to post-process trajectories to remove storms in the tropics.

**Comment by paullric** [comment]
This feature has been added.
