### ISSUE TITLE
performance chart for MPI

### ISSUE THREAD

**Issue by wreckdump** [ClimateGlobalChange/tempestextremes#60]
Hi,

I have been breifly experimenting DetectBlobs with different number of MPI processes, and I can not notice any performance difference compared to serial operation. Do you have any performance chart for MPI operation?

**Comment by paullric** [comment]
Parallelization in TempestExtremes is currently only across files.  Are you using multiple files as input?

**Comment by wreckdump** [comment]
No. I was just using single file.
