### ISSUE TITLE
Poleward maximum value

### ISSUE THREAD

**Issue by yepkids** [ClimateGlobalChange/tempestextremes#61]
Support for finding the maximum value between the candidate point and the two poles (North Pole for lat>=0 and South Pole for lat<0) along the shortest distance path.

**Comment by paullric** [comment]
Would this be in DetectNodes or NodeFileEditor?

**Comment by yepkids** [comment]
Hi Paul,

I think DetectNode is a better fit since it's much faster?

Best,
Yushan


Paul Ullrich ***@***.***> 于 2023年8月11日周五 19:08写道：

**Comment by paullric** [comment]
It may actually be slower to implement in DetectNodes since some nodes are eliminated in the StitchNodes stage.

~ Paul

**Comment by yepkids** [comment]
Yeah. Though, it might make the processes cleaner since one can output all
the columns using DetectNode all together with one command line. But it
doesn't hurt to have one additional command line.

Yushan

Paul Ullrich ***@***.***> 于 2023年8月11日周五 20:39写道：

> It may actually be slower to implement in DetectNodes since some nodes are
> eliminated in the StitchNodes stage.
>
> ~ Paul
>
