### ISSUE TITLE
Command for MPI operations?

### ISSUE THREAD

**Issue by wreckdump** [ClimateGlobalChange/tempestextremes#65]
Is there any examples running DetectNodes with multiple processes using MPI?

I am trying to run it like below, but I don't think it is working.

```
mpiexec -n 2 ./DetectNode -- ....
```
Thanks.

**Comment by paullric** [comment]
DetectNodes only parallelizes over files.  So you’ll need to make sure you’re using the in_data_list argument, which allows you to specify, one in_data per line, in a text file.

**Comment by wreckdump** [comment]
Thank you! It works!
