### ISSUE TITLE
How to detect nodes with local max/min of multiple variables?

### ISSUE THREAD

**Issue by wreckdump** [ClimateGlobalChange/tempestextremes#66]
I would like to find a storm track nodes with local min surface pressure and local max precipitable water (total column water vapor). Is this possible? If so, could you provide an example command options for DetectNodes? If not, is there a workaround for this? Thank you.

**Comment by paullric** [comment]
Does the minimum surface pressure need to be coincident with the maximum precipitable water?  In general I would recommend using --searchbymin PSL then include a closed contour command for both PSL and precipitable water (two closed contour commands can be specified as part of --closedcontourcmd if separated by a semicolon).

**Comment by wreckdump** [comment]
Yes. I would like it if those two variables coincide. Thank you for your suggestion. I would try that.
