### ISSUE TITLE
Feature request: add some metadata to Blobstats

### ISSUE THREAD

**Issue by mariellep** [ClimateGlobalChange/tempestextremes#7]
It would be useful to have some info in the first couple of lines:

Line 1: datetime of first time step (perhaps in format YYYY-MM-DD-HH
Line 2: time resolution? i.e. 6 hourly, 1 daily, etc
Line 3: column headers (timestep, minlat, maxlat, etc) for each variable 

Then a space, and the blobstats output as currently produced

**Comment by paullric** [comment]
Added in commit c9e2f0022d17107b289c4306bf6d751bf2f013e9
