### ISSUE TITLE
Weird track behavior structured vs. unstructured ne240pg3 w/ CAM-SE

### ISSUE THREAD

**Issue by zarzycki** [ClimateGlobalChange/tempestextremes#73]
Tracking some ne240pg3 data for CESM/CAM7.

Generate a connective mesh using a SCRIP grid:

```
zarzycki@derecho4:~/tempest-scripts/for-ben> ~/work/derecho/tempestextremes/bin/GenerateConnectivityFile --in_mesh /glade/campaign/cesm/cesmdata/inputdata/share/scripgrids/ne240pg3_scrip_170628.nc --out_connect test.dat
Arguments:
  --in_mesh <string> ["/glade/campaign/cesm/cesmdata/inputdata/share/scripgrids/ne240pg3_scrip_170628.nc"] 
  --in_data <string> [""] 
  --in_concave <bool> [false] 
  --out_type <string> ["FV"] [FV|CGLL|DGLL]
  --out_np <integer> [4] 
  --out_connect <string> ["test.dat"] 
  --latname <string> ["lat"] 
  --lonname <string> ["lon"] 
------------------------------------------------------------
Loading mesh
..SCRIP Format File detected
..9331198 duplicate nodes detected
..Mesh size: Nodes [3110402] Elements [3110400]
..Done
Calculating connectivity information
..WARNING: 915 small elements found
..Mesh size: Edges [6220800]
..Done
Converting mesh to connectivity format
..Total calculated area: 3.372122629632481e+02 sr
..Done
Writing connectivity file.. Done
------------------------------------------------------------
```

Using this connectivity file and raw CS data works but provides some odd trajectories (cross-equator, for example). I took a look and ncvis does not show a TC in the region TE flags in some cases, but not all cases (i.e., in some cases everything is fine).

So I said, "huh," and interpolated to a regular lat-lon grid w/ bilinear. Tracking on the lat-lon mesh provides mostly similar tracks but eliminates the "poor tracks."

See these two track plots. The one on the top is unstructured and the one on the bottom is structured. Many tracks look "identical" (clipping aside) between the two -- you could download them and toggle 1<->2 and see that. However, a subset of tracks almost seem "rotated." See over the eastern North Atlantic where the TCs are not in the unstructured run but are in the unstruc. It almost seems like they are rotated or moved into the southern hemisphere (east S Pac for example). Also see differences in the S. Indian ocean.

![traj trajectories txt cDEV_ne240pg3_FMTHIST_aicn_x02_UNSTRUCT](https://github.com/ClimateGlobalChange/tempestextremes/assets/10341827/cae62923-202c-445f-b0c7-514283970681)
![traj trajectories txt cDEV_ne240pg3_FMTHIST_aicn_x02_STRUCT](https://github.com/ClimateGlobalChange/tempestextremes/assets/10341827/9bdfcceb-aee2-4ff6-b3a7-8c54efa14ace)

Feels like this is an issue with the connectivity file? SCRIP grid used to make this listed above in the code snippet. I used the SCRIP grid because I am skeptical that the PG meshes are built identically in TempestRemap (and E3SM) and CESM. But the SCRIP grid provides good map weights.

A couple ~6 month track files are attached that were used to make the plots. Code on Derecho here: `/glade/u/home/zarzycki/tempest-scripts/for-ben`

[traj_files.zip](https://github.com/user-attachments/files/15753973/traj_files.zip)

**Comment by zarzycki** [comment]
FWIW, I've verified that the weird points appear in the candidate files (i.e,. the DetectNodes output) so this issue comes before StitchNodes builds the trajectory files.

**Comment by zarzycki** [comment]
Some Q/A

Q: do you have any insights on which days produce the spurious tracks in TE?
A: An example of a spurious TC in the unstructured data occurs here:

```
start   37      2004    9       12      6
        428247  268.248015      -18.866962      9.950583e+04    3.039043e+01    9.950583e+04    2004    9       12      6
        430404  267.687536      -16.549743      9.909413e+04    3.367050e+01    9.909413e+04    2004    9       12      9
        434711  267.467699      -14.330489      9.887332e+04    3.587738e+01    9.887332e+04    2004    9       12      12
        436874  268.031164      -12.149301      9.865784e+04    3.785447e+01    9.865784e+04    2004    9       12      15
        439036  268.843688      -10.591647      9.848638e+04    3.845046e+01    9.848638e+04    2004    9       12      18
        443349  268.812163      -8.435759       9.814655e+04    4.128460e+01    9.814655e+04    2004    9       12      21
        445505  268.500029      -6.122910       9.749317e+04    4.433517e+01    9.749317e+04    2004    9       13      0
        447662  268.968363      -5.342956       9.722453e+04    4.395665e+01    9.722453e+04    2004    9       13      3
        449825  269.531230      -3.156149       9.662968e+04    4.944535e+01    9.662968e+04    2004    9       13      6
        451989  270.687409      -2.312307       9.637187e+04    4.780378e+01    9.637187e+04    2004    9       13      9
        454153  271.843749      -0.093690       9.613654e+04    5.120225e+01    9.613654e+04    2004    9       13      12
        456311  272.531298      0.593345        9.579691e+04    5.353540e+01    9.579691e+04    2004    9       13      15
        458470  272.875086      2.122445        9.516214e+04    5.415626e+01    9.516214e+04    2004    9       13      18
        458484  274.250043      2.867168        9.513748e+04    5.694347e+01    9.513748e+04    2004    9       13      21
        460641  274.250066      4.363076        9.510181e+04    5.504140e+01    9.510181e+04    2004    9       14      0
        462801  274.812486      5.792131        9.501381e+04    5.551117e+01    9.501381e+04    2004    9       14      3
        464950  274.375268      6.606044        9.492492e+04    5.662315e+01    9.492492e+04    2004    9       14      6
        464952  273.687481      7.422261        9.530373e+04    5.228305e+01    9.530373e+04    2004    9       14      9
        464947  273.343793      7.393800        9.578855e+04    4.949247e+01    9.578855e+04    2004    9       14      12
        464938  271.843792      7.402469        9.595459e+04    4.868602e+01    9.595459e+04    2004    9       14      15
        467084  270.469328      8.156018        9.587622e+04    5.176502e+01    9.587622e+04    2004    9       14      18
        464918  268.499964      7.372507        9.587651e+04    5.389792e+01    9.587651e+04    2004    9       14      21
        464916  267.687468      7.431519        9.621298e+04    5.077209e+01    9.621298e+04    2004    9       15      0
        464899  265.374982      7.351259        9.638512e+04    5.226562e+01    9.638512e+04    2004    9       15      3
        464886  263.187748      6.640461        9.657302e+04    4.876402e+01    9.657302e+04    2004    9       15      6
        464873  260.999964      7.285225        9.670877e+04    5.258335e+01    9.670877e+04    2004    9       15      9
        464854  257.874981      7.212256        9.672362e+04    5.037959e+01    9.672362e+04    2004    9       15      12
        464840  255.468788      7.171745        9.669600e+04    4.801213e+01    9.669600e+04    2004    9       15      15
        466979  252.468791      8.498654        9.646016e+04    5.160965e+01    9.646016e+04    2004    9       15      18
        466963  249.906283      8.313103        9.650887e+04    5.271096e+01    9.650887e+04    2004    9       15      21
        469099  246.906811      8.836347        9.652527e+04    5.002956e+01    9.652527e+04    2004    9       16      0
        469086  243.687372      9.376428        9.665296e+04    5.063578e+01    9.665296e+04    2004    9       16      3
        471228  241.249966      10.445150       9.648866e+04    4.901731e+01    9.648866e+04    2004    9       16      6
        475516  237.906943      12.006438       9.639682e+04    5.483032e+01    9.639682e+04    2004    9       16      9
        477657  234.687668      12.907422       9.648355e+04    5.334656e+01    9.648355e+04    2004    9       16      12
        479796  231.312106      14.079456       9.636252e+04    5.448201e+01    9.636252e+04    2004    9       16      15
        484084  227.875451      15.204406       9.615825e+04    5.490055e+01    9.615825e+04    2004    9       16      18
```

Note the storm crosses the equator as a 960mb system. ncvis shows no TC in this region (but one in the NATL at that time, which I suspect is *really* what TE is seeing).

Q: also do you have the SCRIP file?
A: It's ~250MB so best to download it from Derecho: `/glade/campaign/cesm/cesmdata/inputdata/share/scripgrids/ne240pg3_scrip_170628.nc`

Q: also are you using the latest version of TE or the one in my home folder?
A: My own pull, commit: bb914efd77a8621f00caf9f92998cfc5b8650346

**Comment by paullric** [comment]
After an hour of sleuthing, I realized the SCRIP file doesn't match the data beyond the first cubed sphere face.  Could you double check to make sure the run used that particular SCRIP file?  I regenerated a new grid file and the results seem much more reasonable:

```GenerateCSMesh --res 240 --file outCSne240.g
GenerateVolumetricMesh --in outCSne240.g --np 3 --uniform --out outCSne240pg3.g
GenerateConnectivityFile --in_mesh outCSne240pg3.g --out_connect outCSne240pg3_connect.txt```

**Comment by paullric** [comment]
Hmm... Yes, looked into this further.  Something weird was happening with the SCRIP file when RemoveCoincidentNodes() was called on file read.  I've replaced that whole function with something that is slightly slower but far more robust in commit [34f020f](https://github.com/ClimateGlobalChange/tempestextremes/commit/34f020f6495c5f35e37e31b6321f08e3f84e7c92).  Try now?

**Comment by zarzycki** [comment]
Looks like that commit is a good one. Here is the traj file using the NCAR SCRIP file + 34f020f to run GenerateConnectivityFile.

<img width="668" alt="Screenshot 2024-07-08 at 7 15 07 PM" src="https://github.com/ClimateGlobalChange/tempestextremes/assets/10341827/885a4df9-2831-4f11-bde1-f2a2b1c6acf0">

**Comment by paullric** [comment]
Hopefully fixed now!
