### ISSUE TITLE
csv option for StitchNodes seems to be misplacing wind and zs

### ISSUE THREAD

**Issue by ncubukcu** [ClimateGlobalChange/tempestextremes#77]
It looks like 'wind' and 'zs' misplaced if csv option is specified.. See a sample csv file below. This is not apparent when 'gfdl' option is selected since it does not have column names. 

**track_id, year, month, day, hour, i, j, lon, lat, slp, wind, zs
0, 2024, 7, 1, 6, 165, 47, 301.250000, 11.750000, 9.934835e+04, -1.197757e+00, 2.386178e+01**

thanks

**Comment by paullric** [comment]
What is your command line?

**Comment by ncubukcu** [comment]
StitchNodes --in_list OutputFiles.txt --out Tracks.csv --out_file_format "csv" --in_fmt "lon,lat,slp,wind,zs" --range 8.0 --mintime 
"24h" --maxgap "24h" --threshold "wind,>=,10.0,1;lat,<=,50.0,10;lat,>=,-50.0,10;zs,<=,150.0,10"

**Comment by zarzycki** [comment]
What is the DetectNodes line? Is it possible wind and zs are flipped in the DetectNodes output so that StitchNodes is happily reading zs as wind and wind as zs?

**Comment by ncubukcu** [comment]
Oh I see.. The order comes all the way from DetectNodes.  I was not aware of this implicit order. Thank you for letting me know.  Here is was my DetectNodes 

DetectNodes --in_data_list fs_files.txt --out_file_list OutputFiles.txt --timefilter "6hr" --mergedist 6.0 --searchbymin mean_sea_level_pressure --closedcontourcmd "mean_sea_level_pressure,200.0,5.5,0;_DIFF(geopotential(300hPa),geopote
ntial(500hPa)),-58.8,6.5,1.0" --outputcmd "mean_sea_level_pressure,min,0;_DIV(geopotential_at_surface,9.81),max,0;_VECMAG(VAR_10U,VAR_10V),max,2" --latname lat --lonname lon --regional

**Comment by paullric** [comment]
Yes, because GFDL formatted nodefiles have no metadata on the meaning of each column, this information needs to be given to StitchNodes explicitly.  DetectNodes outputs in the order specified by --outputcmd, and so this is the order that needs to be provided to StitchNodes.

~ Paul

**Comment by ncubukcu** [comment]
Noted.. Thank you all..
