### ISSUE TITLE
Fractional area calculation in BlobStats is an order of magnitude too large

### ISSUE THREAD

**Issue by mariellep** [ClimateGlobalChange/tempestextremes#8]
When I convert to km^2 the values are far too large for the patches. 

Example: A block was detected with the bounding box [37N, 12.5E, 54.5N, 36.875E]. The area output, according to BlobStats, is ~0.068

A latitude extent of 17.5 degrees is about 1945 km. A longitude extent of 24.375 degrees is 1565 km at the higher latitude and 2157 km at the lower latitude. So, an area of approximately 3.62x10^6 km^2 ((1565+2157)x0.5x1945)

If we convert that area to a fraction of the spherical surface area,

3.62x10^6/(4 x pi x (6371^2)) = 0.007

**Comment by paullric** [comment]
Not a bug.  Output from BlobStats "area" is in steradians (i.e. between 0 and 4*pi), not fractional area (i.e. between 0 and 1).
