### ISSUE TITLE
Add --start_index option to DetectNodes

### ISSUE THREAD

**Issue by zarzycki** [ClimateGlobalChange/tempestextremes#87]
CESM has moved to a new output strategy in which the first timestep on an output stream is dt, not 0.

So if you request 3-hourly data for a day, you now get...

`3, 6, 9, 12, 15, 18, 21, 0 (next day)`

If you run --timestride 2, TE gives you `3, 9, 15, 21`, which doesn't line up synoptically. Previously, this was fine because your stream always started with hour 0.

Ideally, we'd want to tell TE to stride 2 starting at the 2nd number (either 1 if 0-based or 2 if one-based), so you'd get...

`6, 12, 18, 0`

**Comment by paullric** [comment]
Can you use --time_filter?  Or is that still broken on Derecho?

**Comment by zarzycki** [comment]
> Can you use --time_filter? Or is that still broken on Derecho?

OK, that works -- if it was broken, using `--timefilter 6hr` works now.

Thanks!

**Comment by zarzycki** [comment]
For CESM users (or future me) who stumble across this...

```
write_nstep0=.true.
```

in user_nl_cam will ask the model to output a t=0 timestamp on subdaily output streams. This will recover the old indexing behavior.
